# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import asana
from asana.api.audit_log_api_api import AuditLogAPIApi  # noqa: E501
from asana.rest import ApiException


class TestAuditLogAPIApi(unittest.TestCase):
    """AuditLogAPIApi unit test stubs"""

    def setUp(self):
        self.api = AuditLogAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_audit_log_events(self):
        """Test case for get_audit_log_events

        Get audit log events  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
