# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import asana
from asana.api.task_templates_api import TaskTemplatesApi  # noqa: E501
from asana.rest import ApiException


class TestTaskTemplatesApi(unittest.TestCase):
    """TaskTemplatesApi unit test stubs"""

    def setUp(self):
        self.api = TaskTemplatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_task_template(self):
        """Test case for get_task_template

        Get a task template  # noqa: E501
        """
        pass

    def test_get_task_templates(self):
        """Test case for get_task_templates

        Get multiple task templates  # noqa: E501
        """
        pass

    def test_instantiate_task(self):
        """Test case for instantiate_task

        Instantiate a task from a task template  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
