# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import asana
from asana.api.project_portfolio_settings_api import ProjectPortfolioSettingsApi  # noqa: E501
from asana.rest import ApiException


class TestProjectPortfolioSettingsApi(unittest.TestCase):
    """ProjectPortfolioSettingsApi unit test stubs"""

    def setUp(self):
        self.api = ProjectPortfolioSettingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_project_portfolio_setting(self):
        """Test case for get_project_portfolio_setting

        Get a project portfolio setting  # noqa: E501
        """
        pass

    def test_get_project_portfolio_settings_for_portfolio(self):
        """Test case for get_project_portfolio_settings_for_portfolio

        Get project portfolio settings for a portfolio  # noqa: E501
        """
        pass

    def test_get_project_portfolio_settings_for_project(self):
        """Test case for get_project_portfolio_settings_for_project

        Get project portfolio settings for a project  # noqa: E501
        """
        pass

    def test_update_project_portfolio_setting(self):
        """Test case for update_project_portfolio_setting

        Update a project portfolio setting  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
