# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import asana
from asana.models.portfolio_gid_add_custom_field_setting_body import PortfolioGidAddCustomFieldSettingBody  # noqa: E501
from asana.rest import ApiException


class TestPortfolioGidAddCustomFieldSettingBody(unittest.TestCase):
    """PortfolioGidAddCustomFieldSettingBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPortfolioGidAddCustomFieldSettingBody(self):
        """Test PortfolioGidAddCustomFieldSettingBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = asana.models.portfolio_gid_add_custom_field_setting_body.PortfolioGidAddCustomFieldSettingBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
