# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import asana
from asana.api.organization_exports_api import OrganizationExportsApi  # noqa: E501
from asana.rest import ApiException


class TestOrganizationExportsApi(unittest.TestCase):
    """OrganizationExportsApi unit test stubs"""

    def setUp(self):
        self.api = OrganizationExportsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_organization_export(self):
        """Test case for create_organization_export

        Create an organization export request  # noqa: E501
        """
        pass

    def test_get_organization_export(self):
        """Test case for get_organization_export

        Get details on an org export request  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
