# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import asana
from asana.models.all_of_user_task_list_compact_owner import AllOfUserTaskListCompactOwner  # noqa: E501
from asana.rest import ApiException


class TestAllOfUserTaskListCompactOwner(unittest.TestCase):
    """AllOfUserTaskListCompactOwner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfUserTaskListCompactOwner(self):
        """Test AllOfUserTaskListCompactOwner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = asana.models.all_of_user_task_list_compact_owner.AllOfUserTaskListCompactOwner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
