# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GoalRemoveSubgoalRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'subgoal': 'str'
    }

    attribute_map = {
        'subgoal': 'subgoal'
    }

    def __init__(self, subgoal=None):  # noqa: E501
        """GoalRemoveSubgoalRequest - a model defined in Swagger"""  # noqa: E501
        self._subgoal = None
        self.discriminator = None
        self.subgoal = subgoal

    @property
    def subgoal(self):
        """Gets the subgoal of this GoalRemoveSubgoalRequest.  # noqa: E501

        The goal gid to remove as subgoal from the parent goal  # noqa: E501

        :return: The subgoal of this GoalRemoveSubgoalRequest.  # noqa: E501
        :rtype: str
        """
        return self._subgoal

    @subgoal.setter
    def subgoal(self, subgoal):
        """Sets the subgoal of this GoalRemoveSubgoalRequest.

        The goal gid to remove as subgoal from the parent goal  # noqa: E501

        :param subgoal: The subgoal of this GoalRemoveSubgoalRequest.  # noqa: E501
        :type: str
        """
        if subgoal is None:
            raise ValueError("Invalid value for `subgoal`, must not be `None`")  # noqa: E501

        self._subgoal = subgoal

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GoalRemoveSubgoalRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GoalRemoveSubgoalRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
