# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GoalMetricCurrentValueRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'gid': 'str',
        'resource_type': 'str',
        'current_number_value': 'float'
    }

    attribute_map = {
        'gid': 'gid',
        'resource_type': 'resource_type',
        'current_number_value': 'current_number_value'
    }

    def __init__(self, gid=None, resource_type=None, current_number_value=None):  # noqa: E501
        """GoalMetricCurrentValueRequest - a model defined in Swagger"""  # noqa: E501
        self._gid = None
        self._resource_type = None
        self._current_number_value = None
        self.discriminator = None
        if gid is not None:
            self.gid = gid
        if resource_type is not None:
            self.resource_type = resource_type
        if current_number_value is not None:
            self.current_number_value = current_number_value

    @property
    def gid(self):
        """Gets the gid of this GoalMetricCurrentValueRequest.  # noqa: E501

        Globally unique identifier of the resource, as a string.  # noqa: E501

        :return: The gid of this GoalMetricCurrentValueRequest.  # noqa: E501
        :rtype: str
        """
        return self._gid

    @gid.setter
    def gid(self, gid):
        """Sets the gid of this GoalMetricCurrentValueRequest.

        Globally unique identifier of the resource, as a string.  # noqa: E501

        :param gid: The gid of this GoalMetricCurrentValueRequest.  # noqa: E501
        :type: str
        """

        self._gid = gid

    @property
    def resource_type(self):
        """Gets the resource_type of this GoalMetricCurrentValueRequest.  # noqa: E501

        The base type of this resource.  # noqa: E501

        :return: The resource_type of this GoalMetricCurrentValueRequest.  # noqa: E501
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type):
        """Sets the resource_type of this GoalMetricCurrentValueRequest.

        The base type of this resource.  # noqa: E501

        :param resource_type: The resource_type of this GoalMetricCurrentValueRequest.  # noqa: E501
        :type: str
        """

        self._resource_type = resource_type

    @property
    def current_number_value(self):
        """Gets the current_number_value of this GoalMetricCurrentValueRequest.  # noqa: E501

        *Conditional*. This number is the current value of a goal metric of type number.  # noqa: E501

        :return: The current_number_value of this GoalMetricCurrentValueRequest.  # noqa: E501
        :rtype: float
        """
        return self._current_number_value

    @current_number_value.setter
    def current_number_value(self, current_number_value):
        """Sets the current_number_value of this GoalMetricCurrentValueRequest.

        *Conditional*. This number is the current value of a goal metric of type number.  # noqa: E501

        :param current_number_value: The current_number_value of this GoalMetricCurrentValueRequest.  # noqa: E501
        :type: float
        """

        self._current_number_value = current_number_value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GoalMetricCurrentValueRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GoalMetricCurrentValueRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
