# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GoalRemoveSupportingRelationshipRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'supporting_resource': 'str'
    }

    attribute_map = {
        'supporting_resource': 'supporting_resource'
    }

    def __init__(self, supporting_resource=None):  # noqa: E501
        """GoalRemoveSupportingRelationshipRequest - a model defined in Swagger"""  # noqa: E501
        self._supporting_resource = None
        self.discriminator = None
        self.supporting_resource = supporting_resource

    @property
    def supporting_resource(self):
        """Gets the supporting_resource of this GoalRemoveSupportingRelationshipRequest.  # noqa: E501

        The gid of the supporting resource to remove from the parent goal. Must be the gid of a goal, project, or portfolio.  # noqa: E501

        :return: The supporting_resource of this GoalRemoveSupportingRelationshipRequest.  # noqa: E501
        :rtype: str
        """
        return self._supporting_resource

    @supporting_resource.setter
    def supporting_resource(self, supporting_resource):
        """Sets the supporting_resource of this GoalRemoveSupportingRelationshipRequest.

        The gid of the supporting resource to remove from the parent goal. Must be the gid of a goal, project, or portfolio.  # noqa: E501

        :param supporting_resource: The supporting_resource of this GoalRemoveSupportingRelationshipRequest.  # noqa: E501
        :type: str
        """
        if supporting_resource is None:
            raise ValueError("Invalid value for `supporting_resource`, must not be `None`")  # noqa: E501

        self._supporting_resource = supporting_resource

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GoalRemoveSupportingRelationshipRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GoalRemoveSupportingRelationshipRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
