name: Publish to GitHub Releases

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-n-publish-to-github:
    name: Build and publish to GitHub Releases
    runs-on: ubuntu-latest
    steps:
      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          # Use the newest commit message as the release description
          body: ${{ github.event.head_commit.message }}
